import type { Metadata } from "next";
import styles from './layout.module.scss';
import cn from "classnames/bind";
import "./globals.css";

const cx = cn.bind(styles);

export const metadata: Metadata = {
  title: "컬리즘",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}
